#!/usr/bin/env ruby
require "ripl/multi_line"
require "tempfile"
# Ripl.config[:multi_line_prompt] = ' > '
require "pathname"

selfpath = __FILE__
selfpath = File.readlink(selfpath) if File.lstat(selfpath).symlink?
scriptdir = File.expand_path(File.dirname(selfpath) + "/..")

# --user-dir PATH (or --user-dir=PATH): use PATH as the config/data directory
# instead of ~/.config/vimamsa. Consumed here (and removed from ARGV) so it is
# available before anything reads the user dir, including the listen check below.
if (i = ARGV.index("--user-dir"))
  $vma_user_dir = File.expand_path(ARGV[i + 1]) if ARGV[i + 1]
  ARGV.slice!(i, 2)
elsif (arg = ARGV.find { |a| a.start_with?("--user-dir=") })
  $vma_user_dir = File.expand_path(arg.split("=", 2)[1])
  ARGV.delete(arg)
end
$vma_user_dir ||= File.expand_path("~/.config/vimamsa")

# If process is already running, open the parameter file in the running process and exit.
listen_dir = File.join($vma_user_dir, "listen")
if File.exist?(listen_dir) and !ARGV[0].nil?
  tmpf = Tempfile.new("vmarun", listen_dir)
  fp = tmpf.path
  paramfn = File.expand_path(ARGV[0])
  puts paramfn
  tmpf.write(paramfn)
  tmpf.close
  tstart = Time.new
  timeout = false
  while File.exist?(fp)
    sleep 0.001
    if Time.new - tstart > 0.5
      timeout = true
      break
    end
  end
  exit(0) if !timeout
end

$LOAD_PATH.unshift(File.expand_path("lib"))
$LOAD_PATH.unshift(File.expand_path("ext"))

require "vimamsa"
include Vimamsa

# Persist crash/segfault debug info (native stderr dump + structured reports)
# to ~/.config/vimamsa/crash/ .
Vimamsa::CrashHandler.setup

# Ilib:ext
# r rbvma -e "puts VMA.new.run"
$vmag = Vimamsa::VMAgui.new()
$vmag.run
